### ISSUE TITLE
drush::upgrade_pear - Malformed version number string found

### ISSUE THREAD

**Issue by dkingofpa** [msonnabaum/chef-drush#12]
@patcon Have you run across this error before?

```
ArgumentError: php_pear[pear] (drush::upgrade_pear line 22) had an error: ArgumentError: Malformed version number string found
/usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/version.rb:187:in `initialize'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/drush/recipes/upgrade_pear.rb:24:in `new'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/drush/recipes/upgrade_pear.rb:24:in `block (2 levels) in from_file'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource/conditional.rb:80:in `call'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource/conditional.rb:80:in `evaluate_block'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource/conditional.rb:72:in `evaluate'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource/conditional.rb:65:in `continue?'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource.rb:466:in `block in should_skip?'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource.rb:465:in `each'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource.rb:465:in `find'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource.rb:465:in `should_skip?'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource.rb:436:in `run_action'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/runner.rb:45:in `run_action'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/runner.rb:81:in `each'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/runner.rb:81:in `block in converge'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource_collection.rb:94:in `block in execute_each_resource'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/resource_collection.rb:92:in `execute_each_resource'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/runner.rb:76:in `converge'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/client.rb:312:in `converge'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/client.rb:160:in `run'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/application/solo.rb:192:in `block in run_application'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/application/solo.rb:183:in `loop'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/application/solo.rb:183:in `run_application'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/lib/chef/application.rb:67:in `run'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/chef-0.10.8/bin/chef-solo:25:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.2-p320/bin/chef-solo:19:in `load'
/usr/local/rvm/gems/ruby-1.9.2-p320/bin/chef-solo:19:in `<main>'
vagrant@drupal:~$
vagrant@drupal:~$
vagrant@drupal:~$ pear -V 2>&1 | head -1 | awk '{print $NF}' | tr -d '\n'
1.9.4
vagrant@drupal:~$
```

**Comment by dkingofpa** [comment]
#10 appears to fix this issue.  Closing.
